import { COLORS } from "./theme.js";

export const TICKER = [
  "UI/UX DESIGNER",
  "GRAPHIC DESIGNER",
  "SOFTWARE ENGINEER",
  "VIDEO EDITOR",
  "WRITER SINCE 13",
  "STILL FIGURING IT OUT",
];

export const PROJECTS = [
  {
    tag: "BRAND IDENTITY + UI/UX case study",
    title: "Aegis",
    blurb: "A full brand system for a recycling app — logo, UI/UX case study, and social assets. Built with the intention of making recycling fun.",
    tools: ["Affinity Designer", "Affinity Photo", "Figma", ],
    grad: `linear-gradient(135deg, ${COLORS.blue}, ${COLORS.indigo})`,
    link: "https://drive.google.com/drive/folders/1-zlIpO40P5GupFlCgC3pfbySsbSh_FA0?usp=drive_link",
    image: "/covers/Aegis.png",
  },
  {
    tag: "PRODUCT DESIGN + BUILD",
    title: "Oya Deliver",
    blurb: "A grocery delivery platform designed and shipped solo — from Figma wireframes to a deployed React app with cart, auth, and order history.",
    tools: ["Figma", "React", "Vercel"],
    grad: `linear-gradient(135deg, #FFD561, ${COLORS.cyan})`,
    link: "https://grocery-delivery-platform-eta.vercel.app",
    image: "/covers/Oya-deliver.png",
  },
  {
    tag: "Brand Identity + Landing Page Design",
    title: "Misukiε",
    blurb: "A full brand identity for a Japanese inspired clothing brand — logo, Prototyping, and UI/UX design for the Landing page.",
    tools: ["Figma "],
    grad: `linear-gradient(135deg, ${COLORS.cyan}, ${COLORS.indigo})`,
    link: "https://drive.google.com/drive/folders/14wJ6JU-OIsLMX4NH7jcoVXVOW7NKb6ZP?usp=drive_link",
    image: "/covers/Misukie.png",
  },
  {
    tag: "Mobile Shopping App",
    title: "Pick Go",
    blurb: "Mobile-first shopping app to make fashion discovery fast, intuitive & enjoyable— designed to be fast, simple, and easy to use on the go.",
    tools: ["Figma"],
    grad: `linear-gradient(135deg, ${COLORS.ink}, ${COLORS.blue})`,
    link: "https://drive.google.com/drive/folders/1UIqJdOGJVhbV6NgRRlMbTSMTmEB7c5u6?usp=drive_link",
    image: "/covers/pick-go.png",
  },
  {
    tag: "UI CONCEPT",
    title: "Tonal Redesign",
    blurb: "A dark, glassmorphic reimagining of a fitness app interface — charcoal and forest green, built for focus.",
    tools: ["Figma"],
    grad: `linear-gradient(135deg, #2F3E36, ${COLORS.indigo})`,
    link: "https://drive.google.com/drive/folders/1Ix5vKsMWfUJdakhrvn8LPmcm06Nv9LDC?usp=drive_link",
    image: "/covers/Tonal-redesign.png",
  },
   {
    tag: "Brand Identity + Landing Page Design",
    title: "PEN",
    blurb: "PEN is a creative design tool brand built around the idea of freedom of expression- UI/UX design, Prototyping.",
    tools: ["Figma"],
    grad: `linear-gradient(135deg, ${COLORS.ink}, ${COLORS.blue})`,
    link: "https://drive.google.com/drive/folders/1UIqJdOGJVhbV6NgRRlMbTSMTmEB7c5u6?usp=drive_link",
    image: "/covers/Pen.png",
  },
   {
    tag:"Editorial Flyer",
    title: "Bloom & Learn",
    blurb: "An editorial flyer for a flower shop, designed to be visually striking, complementing the brand identity - Poster design, typography, and layout.",
    tools: ["Canva", "Figma"],
    grad: `linear-gradient(135deg, #2F3E36, ${COLORS.indigo})`,
    link: "https://drive.google.com/drive/folders/1IAWwaXi9SFNqkLpFXZ2auV9dV_HNl8TG?usp=drive_link",
    image: "/covers/Bloom-learn.png",
  },
    {
    tag:"Editorial Flyer",
    title: "Milan Couture",
    blurb: "An editorial flyer for a fashion brand, designed to be visually striking, complementing the brand identity - Poster design, typography, and layout.",
    tools: ["Canva", "Figma"],
    grad: `linear-gradient(135deg, #2F3E36, ${COLORS.indigo})`,
    link: "https://drive.google.com/drive/folders/17_0JRiqcB28SvDyESITN6xsG9gL0Gfws?usp=drive_link",
    image: "/covers/Milan-couture.png",
  },
    {
    tag:"Landing Page",
    title: "The Prodigy Awards",
    blurb: "A landing page for a youth awards event, designed to be visually striking, complementing the brand identity - UI/UX Design, Prototyping.",
    tools: ["Figma"],
    grad: `linear-gradient(135deg, #2F3E36, ${COLORS.indigo})`,
    link: "https://drive.google.com/drive/folders/1sBqxdmhBE7gHSkCQT6BSJrYTQYMuonvF?usp=drive_link",
    image: "/covers/Prodigy-awards.png",
  },
    {
    tag:"Editorial Flyer",
    title: "Opulence",
    blurb: "An editorial flyer for a luxury lifestyle brand, designed to be visually striking, complementing the brand identity - Poster design, typography, and layout.",
    tools: ["Canva", "Figma"],
    grad: `linear-gradient(135deg, #2F3E36, ${COLORS.indigo})`,
    link: "https://drive.google.com/drive/folders/1BXebo7M8p76IvAndVhMeOIPdUCkx2plC?usp=drive_link",
    image: "/covers/Opulence.png",
  },
    {
    tag:"Flyer",
    title: "Innovations Expo",
    blurb: "An flyer for an innovations expo, having a modern and dynamic design, complementing the brand identity - Poster design, typography, and layout.",
    tools: ["Canva", "Figma"],
    grad: `linear-gradient(135deg, #2F3E36, ${COLORS.indigo})`,
    link: "https://drive.google.com/drive/folders/1CoF-sMyst-ISWpIRKUOE4z7uMXKrAUk3?usp=drive_link",
    image: "/covers/Innovations-expo.png",
  },
    {
    tag:" Flyer",
    title: "Art Exhibition",
    blurb: "An flyer for an art exhibition, designed to be visually striking, complementing the brand identity - Poster design, typography, and layout.",
    tools: ["Canva", "Figma"],
    grad: `linear-gradient(135deg, #2F3E36, ${COLORS.indigo})`,
    link: "https://drive.google.com/drive/folders/1GpZ1LDtb-jfZtCB4rMCYX7YV1hr2G5rr?usp=drive_link",
    image: "/covers/Art-exhibition.png",
  },
    {
    tag:"Flyer - Client Work",
    title: "Austine Gadgets",
    blurb: "A flyer for a tech store, designed to be visually striking, complementing the brand identity - Poster design, typography, and layout.",
    tools: ["Canva", "Figma"],
    grad: `linear-gradient(135deg, #2F3E36, ${COLORS.indigo})`,
    link: "https://drive.google.com/drive/folders/1tL-Vr9KKa98F7JUA0wjNa4mcciVQqOdz?usp=drive_link",
    image: "/covers/Austine-gadgets.png",
  },
   {
    tag:"Logo - Client Work",
    title: "Solar Lit Spaces",
    blurb: "A logo for a  store, designed to be visually striking, complementing the brand identity - Logo design, typography, and layout.",
    tools: ["Figma"],
    grad: `linear-gradient(135deg, #2F3E36, ${COLORS.indigo})`,
    link: "https://drive.google.com/drive/folders/1WzrMpv5M02QULZW1ddHLqh7_SXGq9bjm?usp=drive_link",
    image: "/covers/Solar.png",
  },
  {
    tag: "CONTENT PIPELINE",
    title: "Shorts, Automated",
    blurb: "A mobile-first content pipeline for short-form video — scripting, voice, and edit, end to end.",
    tools: ["CapCut", "ElevenLabs", "Canva"],
    grad: `linear-gradient(135deg, ${COLORS.blue}, #FFD561)`,
    link: "https://drive.google.com/drive/folders/1goJSfGdNaz76m_T91ilhpDGL_03H4Uid?usp=drive_link",
    image: "https://i.pinimg.com/736x/93/cb/8f/93cb8f320e84f9747a7c622c361c65e2.jpg"
  },
];