import { COLORS } from "./theme.js";

export const TICKER = [
  "UI/UX DESIGNER",
  "GRAPHIC DESIGNER",
  "SOFTWARE ENGINEER",
  "VIDEO EDITOR",
  "WRITER SINCE 13",
  "STILL FIGURING IT OUT",
];

export const PROJECTS = [
  {
    tag: "BRAND IDENTITY + UI/UX case study",
    title: "Aegis",
    blurb: "A full brand system for a recycling app — logo, UI/UX case study, and social assets. Built with the intention of making recycling fun.",
    tools: ["Affinity Designer", "Affinity Photo", "Figma", ],
    grad: `linear-gradient(135deg, ${COLORS.blue}, ${COLORS.indigo})`,
    link: "https://drive.google.com/drive/folders/1-zlIpO40P5GupFlCgC3pfbySsbSh_FA0?usp=drive_link",
    image: "/covers/Aegis.png",
  },
  {
    tag: "PRODUCT DESIGN + BUILD",
    title: "Oya Deliver",
    blurb: "A grocery delivery platform designed and shipped solo — from Figma wireframes to a deployed React app with cart, auth, and order history.",
    tools: ["Figma", "React", "Vercel"],
    grad: `linear-gradient(135deg, #FFD561, ${COLORS.cyan})`,
    link: "https://grocery-delivery-platform-eta.vercel.app",
    image: "/covers/Oya-deliver.png",
  },
  {
    tag: "Brand Identity + Landing Page Design",
    title: "Misukiε",
    blurb: "A full brand identity for a Japanese inspired clothing brand — logo, color palette, and UI/UX design for the Landing page.",
    tools: ["Figma "],
    grad: `linear-gradient(135deg, ${COLORS.cyan}, ${COLORS.indigo})`,
    link: "https://drive.google.com/drive/folders/14wJ6JU-OIsLMX4NH7jcoVXVOW7NKb6ZP?usp=drive_link",
    image: "/covers/Misukie.png",
  },
  {
    tag: "Mobile Shopping App",
    title: "Pick Go",
    blurb: "Mobile-first shopping app to make fashion discovery fast, intuitive & enjoyable— designed to be fast, simple, and easy to use on the go.",
    tools: ["Figma"],
    grad: `linear-gradient(135deg, ${COLORS.ink}, ${COLORS.blue})`,
    link: "https://drive.google.com/drive/folders/1UIqJdOGJVhbV6NgRRlMbTSMTmEB7c5u6?usp=drive_link",
    image: "/covers/pick-go.png",
  },
  {
    tag: "UI CONCEPT",
    title: "Tonal Redesign",
    blurb: "A dark, glassmorphic reimagining of a fitness app interface — charcoal and forest green, built for focus.",
    tools: ["Figma"],
    grad: `linear-gradient(135deg, #2F3E36, ${COLORS.indigo})`,
    link: "https://drive.google.com/drive/folders/1Ix5vKsMWfUJdakhrvn8LPmcm06Nv9LDC?usp=drive_link",
    image: "/covers/Tonal-redesign.png",
  },
   {
    tag: "Brand Identity + Landing Page Design",
    title: "PEN",
    blurb: "PEN is a creative design tool brand built around the idea of freedom of expression- UI/UX design for the Landing page.",
    tools: ["Figma"],
    grad: `linear-gradient(135deg, ${COLORS.ink}, ${COLORS.blue})`,
    link: "https://drive.google.com/drive/folders/1UIqJdOGJVhbV6NgRRlMbTSMTmEB7c5u6?usp=drive_link",
    image: "/covers/Pen.png",
  },
   {
    tag:"Edittorial Flyer",
    title: "Bloom & Learn",
    blurb: "An editorial flyer for a flower shop, designed to be visually striking, complementing the brand identity - Poster design, typography, and layout.",
    tools: ["Canva"],
    grad: `linear-gradient(135deg, #2F3E36, ${COLORS.indigo})`,
    link: "https://drive.google.com/drive/folders/1IAWwaXi9SFNqkLpFXZ2auV9dV_HNl8TG?usp=drive_link",
    image: "/covers/Bloom-learn.png",
  },
  {
    tag: "CONTENT PIPELINE",
    title: "Shorts, Automated",
    blurb: "A mobile-first content pipeline for short-form video — scripting, voice, and edit, end to end.",
    tools: ["CapCut", "ElevenLabs", "Canva"],
    grad: `linear-gradient(135deg, ${COLORS.blue}, #FFD561)`,
    link: "PASTE_DRIVE_FOLDER_LINK_HERE",
  },
];